# Permalinks
permalink:           pretty

# Setup
title:               "Roundabout"
tagline:             "A Jekyll theme."
url:                 http://blvd.space
baseurl:             "/roundabout"

# Pagination (uncomment if you want posts to paginate)
# paginate:            1
# paginate_path:       "/page/:num/"

# Google Analytics (uncomment if you have any)
# analytics_id:        "id"

# List of time zones supported in the TZ database
# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:            UTC

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _scss
  style:            :compressed

# About/contact
author:
  name:              Resi Respati
  url:               https://resir014.xyz
  email:             resir014@blvd.space

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/blvdgroup/roundabout

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
